# Generated by Django 4.2.6 on 2023-12-03 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=250)),
                ('post_brief', models.CharField(max_length=450)),
                ('main_photo', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[500, None], upload_to='photography/')),
                ('main_photo_alt', models.CharField(max_length=100)),
                ('photo_1', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[500, None], upload_to='photography/')),
                ('photo_1_alt', models.CharField(max_length=100)),
                ('photo_2', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[500, None], upload_to='photography/')),
                ('photo_2_alt', models.CharField(max_length=100)),
                ('photo_3', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[500, None], upload_to='photography/')),
                ('photo_3_alt', models.CharField(max_length=100)),
                ('photo_4', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[500, None], upload_to='photography/')),
                ('photo_4_alt', models.CharField(max_length=100)),
                ('photo_5', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[500, None], upload_to='photography/')),
                ('photo_5_alt', models.CharField(max_length=100)),
                ('photo_6', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[500, None], upload_to='photography/')),
                ('photo_6_alt', models.CharField(max_length=100)),
                ('photo_7', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[500, None], upload_to='photography/')),
                ('photo_7_alt', models.CharField(max_length=100)),
                ('photo_8', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[500, None], upload_to='photography/')),
                ('photo_8_alt', models.CharField(max_length=100)),
                ('photo_9', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[500, None], upload_to='photography/')),
                ('photo_9_alt', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photography_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
